pipeline {
	agent any 
	
	stages {
	    stage('Checkout') {
	        steps {
			checkout scm			       
		      }}
		stage('Build') {
	           steps {
			  sh '/opt/apache-tomcat-9.0.99/bin/mvn install'
	                 }}
		stage('Deployment'){
		   steps {
		sh 'cp target/Project1.war /opt/apache-tomcat-9.0.99/webapps'
			}}	
}}
